services:
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: wo-prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.retention.time=30d"
      - "--web.enable-admin-api"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/config:/etc/prometheus
      - prometheus_data:/prometheus
    networks:
      - monitoring
      - wise-owl-network
    environment:
      - TZ=UTC
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=9090"
      - "prometheus.io/path=/metrics"

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.0.0
    container_name: wo-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SMTP_ENABLED=false
      - TZ=UTC
    labels:
      - "prometheus.io/scrape=true"
      - "prometheus.io/port=3000"
      - "prometheus.io/path=/metrics"

  # Node Exporter for system metrics
  node-exporter:
    image: prom/node-exporter:latest
    container_name: wo-node-exporter
    restart: unless-stopped
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
      - "--collector.netdev.device-exclude=^lo$$"
      - "--collector.textfile.directory=/var/lib/node_exporter/textfile_collector"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - node_exporter_data:/var/lib/node_exporter
    networks:
      - monitoring
    expose:
      - 9100

  # cAdvisor for container metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: wo-cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - monitoring
    expose:
      - 8080
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      - "--store_container_labels=false"

  # System monitoring tools container
  system-tools:
    image: nicolaka/netshoot:latest
    container_name: wo-system-tools
    restart: unless-stopped
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/scripts:/scripts:ro
    command: sleep infinity
    environment:
      - TZ=UTC
    labels:
      - "monitoring.role=system-tools"

  # Log aggregation with Loki
  loki:
    image: grafana/loki:2.9.0
    container_name: wo-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki:/etc/loki
      - loki_data:/loki
    networks:
      - monitoring
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - TZ=UTC

  # Promtail for log collection
  promtail:
    image: grafana/promtail:2.9.0
    container_name: wo-promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./monitoring/promtail:/etc/promtail
    networks:
      - monitoring
    command: -config.file=/etc/promtail/config.yml
    environment:
      - TZ=UTC
    depends_on:
      - loki

  # Alertmanager for notifications
  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: wo-alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager:/etc/alertmanager
      - alertmanager_data:/alertmanager
    networks:
      - monitoring
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"
      - "--web.external-url=http://localhost:9093"
    environment:
      - TZ=UTC

  # MongoDB Exporter for database metrics
  mongodb-exporter:
    image: percona/mongodb_exporter:0.39
    container_name: wo-mongodb-exporter
    restart: unless-stopped
    command:
      - "--mongodb.uri=${MONGODB_URI}"
      - "--collect-all"
      - "--compatible-mode"
    networks:
      - monitoring
      - wise-owl-network
    expose:
      - 9216
    environment:
      - TZ=UTC
    depends_on:
      - mongodb

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: wo-jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"
      - "14268:14268"
    networks:
      - monitoring
      - wise-owl-network
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - TZ=UTC

volumes:
  prometheus_data:
  grafana_data:
  node_exporter_data:
  loki_data:
  alertmanager_data:

networks:
  monitoring:
    driver: bridge
    name: wo-monitoring
  wise-owl-network:
    external: true
    name: wise-owl-network
