services:
  mongodb:
    image: mongo:latest
    container_name: wo-mongodb-dev
    restart: unless-stopped
    env_file:
      - ./.env.local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db

volumes:
  mongo_data_dev:
