services:
  db:
    image: postgres:15-alpine
    container_name: bnn-db-dev
    restart: unless-stopped
    env_file: [./.env.local]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  postgres_data_dev:
