services:
  nginx:
    image: nginx:stable-alpine
    container_name: wo-nginx
    restart: unless-stopped
    ports: ["8080:80"]
    volumes: ["./nginx:/etc/nginx/conf.d:ro"]
    networks:
      - wise-owl-network
    depends_on:
      - users-service
      - content-service
      - quiz-service

  users-service:
    container_name: wo-users-service
    image: wo-users-service:latest
    restart: unless-stopped
    env_file: [./.env.production]
    environment:
      - DB_NAME=users_db
      - DB_TYPE=documentdb
    networks:
      - wise-owl-network

  content-service:
    container_name: wo-content-service
    image: wo-content-service:latest
    restart: unless-stopped
    env_file: [./.env.production]
    environment:
      - DB_NAME=content_db
      - DB_TYPE=documentdb
    networks:
      - wise-owl-network

  quiz-service:
    container_name: wo-quiz-service
    image: wo-quiz-service:latest
    restart: unless-stopped
    env_file: [./.env.production]
    environment:
      - DB_NAME=quiz_db
      - DB_TYPE=documentdb
    networks:
      - wise-owl-network

networks:
  wise-owl-network:
    driver: bridge
    name: wise-owl-network
