root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ./services/content/cmd"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", ".git"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["services/content", "lib", "gen"]
  include_ext = ["go", "tpl", "tmpl", "html", "json"]
  include_file = []
  kill_delay = "2s"
  log = "build-errors.log"
  poll = true
  poll_interval = 500
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
