#!/bin/bash
# Script Organization Summary for Wise Owl Project

show_organization() {
    echo "📁 Wise Owl Scripts Organization"
    echo "================================"
    echo ""
    echo "🎯 Main Entry Point:"
    echo "   ./wise-owl [category] [command]"
    echo ""
    echo "📂 Directory Structure:"
    echo ""
    echo "scripts/"
    echo "├── development/          # Development environment management"
    echo "│   ├── dev.sh           # Main development script"
    echo "│   ├── dev-watch.sh     # Hot reload development"
    echo "│   └── test-dev.sh      # Health checks and testing"
    echo "├── deployment/          # Production deployment"
    echo "│   ├── setup-raspberry-pi-generic.sh  # Server setup"
    echo "│   └── deploy-wise-owl.sh             # App deployment"
    echo "├── utils/               # Shared utilities"
    echo "│   └── common.sh        # Common functions and utilities"
    echo "└── README.md            # Comprehensive documentation"
    echo ""
    echo "🚀 Quick Commands:"
    echo ""
    echo "Development:"
    echo "  ./wise-owl dev setup    # Initial environment setup"
    echo "  ./wise-owl dev start    # Start all services"
    echo "  ./wise-owl dev watch    # Hot reload development"
    echo "  ./wise-owl dev test     # Health check services"
    echo "  ./wise-owl dev status   # Show service status"
    echo "  ./wise-owl dev logs     # View service logs"
    echo "  ./wise-owl dev stop     # Stop all services"
    echo "  ./wise-owl dev clean    # Clean up everything"
    echo ""
    echo "Deployment:"
    echo "  ./wise-owl deploy setup # Setup production server"
    echo "  ./wise-owl deploy app   # Deploy application"
    echo ""
    echo "📚 Documentation:"
    echo "  scripts/README.md       # Detailed script documentation"
    echo "  .github/copilot-instructions.md  # AI assistant guidelines"
    echo ""
    echo "✨ Key Features:"
    echo "  • Unified command interface"
    echo "  • Colored output and progress indicators"
    echo "  • Error handling and validation"
    echo "  • Docker/Docker Compose compatibility"
    echo "  • Environment file management"
    echo "  • Health checking utilities"
    echo "  • Shared utility functions"
    echo ""
}

show_organization
